export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
      <h1 className="font-display text-3xl font-semibold text-primary">Terms & Privacy</h1>
      <p className="mt-2 text-sm text-neutral-soft">Last updated: July 2026</p>

      <div className="mt-10 space-y-8 text-sm leading-relaxed text-neutral-soft">
        <section>
          <h2 className="font-display text-lg font-semibold text-primary">1. About this project</h2>
          <p className="mt-2">
            GigMatch AI is a demonstration full-stack application built to showcase AI-assisted
            matching between freelancers and gigs. It is not a commercial service, and no real
            payments are processed anywhere in this application.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-primary">2. Accounts</h2>
          <p className="mt-2">
            You&apos;re responsible for the accuracy of the information you provide when creating an
            account, and for keeping your login credentials confidential. You may sign in with an
            email and password or with Google.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-primary">3. Posting gigs</h2>
          <p className="mt-2">
            Anyone with an account may post a gig. Gig content should be accurate and should not
            include anything illegal, misleading, or abusive. Only the account that posted a gig may
            edit or delete it.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-primary">4. AI features</h2>
          <p className="mt-2">
            Fit scores, recommendation reasons, and chat assistant responses are generated by a
            large language model and are provided for guidance only. They may occasionally be
            inaccurate, and shouldn&apos;t be treated as a guarantee of outcome.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-primary">5. Data & privacy</h2>
          <p className="mt-2">
            We store the account details you provide (name, email, hashed password or Google
            identifier, skills, and the gigs you post) in order to run the platform. Recently viewed
            gigs are tracked only to improve your own recommendations, and passwords are never stored
            in plain text.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-primary">6. Changes</h2>
          <p className="mt-2">
            These terms may be updated as the project evolves. Continued use of the platform after a
            change means you accept the updated terms.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-primary">7. Contact</h2>
          <p className="mt-2">
            Questions about these terms can be sent to devalmahmud@gmail.com or through the{' '}
            <a href="/contact" className="font-medium text-secondary hover:underline">
              Contact page
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  )
}
